- name: Install nginx
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
  become: yes

- name: Start nginx service
  service:
    name: nginx
    state: started
  become: yes

- name: Copy the nginx service
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: u=rw,g=,o=
  notify: restart nginx
  become: yes
